Removed classes to support PowerShell 4.0
PowerShell/GPRegistryPolicyParser pull request #1
Opened 2017-04-06 11:31 UTC by bobbytreed

2017-05-19 20:52 UTC, Indhukrishna commented on GPRegistryPolicyParser.psm1
> +        [Parameter(Mandatory)]
Why are the positional parameters removed?

2017-05-19 20:54 UTC, Indhukrishna commented on GPRegistryPolicyParser.psm1
>  C:\PS> Parse-PolFile -Path "C:\Registry.pol"
The comment needs to be updated to match the function name

2017-05-19 20:55 UTC, Indhukrishna commented on GPRegistryPolicyParser.psm1
> +    Write-Host "Creating key $($RP.KeyName)"
Please try not to use Write-Host inside scripts http://www.jsnover.com/blog/2013/12/07/write-host-considered-harmful/

2017-05-19 20:57 UTC, Indhukrishna requested changes
Please update the code review with the requested changes.

2017-06-09 23:51 UTC, zjalali commented on GPRegistryPolicyParser.psm1
> +        [ValidateSet("HKLM", "HKCU")]
>"HKLM", "HKCU" [](start = 21, length = 14)

This change will break GPRegistryPolicy module.

2017-06-09 23:53 UTC, zjalali commented on GPRegistryPolicyParser.psm1
> +        [ValidateSet("HKLM", "HKCU")]
All changes in function signatures could break GPRegistryPolicy module.

---
In reply to: [121241843](https://github.com/PowerShell/GPRegistryPolicyParser/pull/1#discussion_r121241843) [](ancestors = 121241843)

2017-06-09 23:58 UTC, zjalali commented on GPRegistryPolicyParser.psm1
> -            $Data = $RegKey.GetValue($ValueName,$null,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames)
>,[Microsoft.Win32.RegistryValueOptions]::DoNotExpandEnvironmentNames [](start = 53, length = 68)

This flag is required here. Why was it removed?

2017-06-09 23:59 UTC, zjalali commented on GPRegistryPolicyParser.psm1
> -        if ($PSVersionTable.PSEdition -ieq 'Core')
>$PSVersionTable.PSEdition -ieq 'Core') [](start = 12, length = 38)

This coded was added for PS Core on NanoServer. Why was it removed?

2017-06-10 00:05 UTC, zjalali commented
The `readme.md` file needs an update as well.

2017-06-10 00:06 UTC, zjalali requested changes
Please review the comments on the documents.

2020-07-21 19:47 UTC, closed without merging